name: Build and Push Docker Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image: image
          branch: master
          dockerfile: ./Docker/Dockerfile

      - name: Login to Azure2
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Image to Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: acrstorelink9696
          containerAppName: test
          resourceGroup: rg-application-storelink-nonprd
          imageToDeploy: acrstorelink9696.azurecr.io/app:latest
