name: Build and Push Docker Image

on:
  push:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          branch: master

  deploy:
    name: 'Deployment'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Image to Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: acr12b0aa02
          containerAppName: nginx
          resourceGroup: example-container-app-7b9ea612651c6d2d
          imageToDeploy: acr12b0aa02.azurecr.io/app:latest
