name: Trigger auto deployment for nonprd-storelink

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/nonprd-storelink-AutoDeployTrigger-c9a326d5-6291-47d8-9e16-2cd8d8667be8.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NONPRDSTORELINK_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrstorelink9696.azurecr.io
          registryUsername: ${{ secrets.NONPRDSTORELINK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NONPRDSTORELINK_REGISTRY_PASSWORD }}
          containerAppName: nonprd-storelink
          resourceGroup: rg-application-storelink-nonprd
          imageToBuild: acrstorelink9696.azurecr.io/nonprd-storelink:${{ github.sha }}
          
            

     

